"""Bundled "Try a sample" frame sequences for :class:`RealHybridStitchPanel`
(roadmap Phase 6.3, issue #17: "Bundled sample projects").

Discovers the synthetic sample sequences generated by
``gui/scripts/generate_sample_sequences.py`` into
``gui/resources/samples/<name>/frame_NN.png`` and exposes them as an ordered
mapping of a human-readable label to the frame paths in scroll order, so a
new user can load one straight into the panel's sequence sidebar and explore
every tool tab on real (synthetic) data immediately.

These are small, entirely procedurally-drawn test patterns (flat shapes,
gradients, simple line art) -- never real source art -- see the generator
script's own docstring for why.
"""

from __future__ import annotations

from pathlib import Path

SAMPLES_DIR = Path(__file__).resolve().parents[3] / "resources" / "samples"

# Maps the on-disk directory name to a short, human-readable menu label.
_LABELS: dict[str, str] = {
    "scroll_a_panels": "Sample: Color Panels",
    "scroll_b_lineart": "Sample: Line Art",
    "scroll_c_textgrid": "Sample: Text Grid",
}


def list_sample_sequences(samples_dir: Path = SAMPLES_DIR) -> dict[str, list[str]]:
    """Return ``{label: [frame_path, ...]}`` for every bundled sample
    sequence found under ``samples_dir``, in scroll order. Missing or empty
    directories are silently skipped (e.g. a stripped-down install), so
    callers should handle an empty result rather than assume samples always
    exist."""
    result: dict[str, list[str]] = {}
    if not samples_dir.is_dir():
        return result
    for sub in sorted(samples_dir.iterdir()):
        if not sub.is_dir():
            continue
        frames = sorted(p for p in sub.iterdir() if p.suffix.lower() == ".png")
        if not frames:
            continue
        label = _LABELS.get(sub.name, sub.name)
        result[label] = [str(p) for p in frames]
    return result


__all__ = ["SAMPLES_DIR", "list_sample_sequences"]
