// AUTO-GENERATED by scripts/generate-nav.mjs from ../mkdocs.yml — do not edit by hand.
export interface NavLeaf {
  title: string;
  kind: "md" | "notebook";
  path: string;
  source: string;
}
export interface NavExternal {
  title: string;
  kind: "external";
  href: string;
}
export interface NavSection {
  title: string;
  kind: "section";
  children: NavNode[];
}
export type NavNode = NavLeaf | NavExternal | NavSection;

export const navTree: NavNode[] = [
  {
    "title": "Home",
    "kind": "md",
    "path": "/",
    "source": "index.md"
  },
  {
    "title": "Architecture",
    "kind": "md",
    "path": "/ARCHITECTURE",
    "source": "ARCHITECTURE.md"
  },
  {
    "title": "Development",
    "kind": "md",
    "path": "/DEVELOPMENT",
    "source": "DEVELOPMENT.md"
  },
  {
    "title": "Testing",
    "kind": "md",
    "path": "/TESTING",
    "source": "TESTING.md"
  },
  {
    "title": "Dependencies",
    "kind": "md",
    "path": "/DEPENDENCIES",
    "source": "DEPENDENCIES.md"
  },
  {
    "title": "Dependency Policy",
    "kind": "md",
    "path": "/DEPENDENCY_POLICY",
    "source": "DEPENDENCY_POLICY.md"
  },
  {
    "title": "Documentation Standards",
    "kind": "md",
    "path": "/DOCUMENTATION_STANDARDS",
    "source": "DOCUMENTATION_STANDARDS.md"
  },
  {
    "title": "Benchmarks",
    "kind": "md",
    "path": "/BENCHMARKS",
    "source": "BENCHMARKS.md"
  },
  {
    "title": "Troubleshooting",
    "kind": "md",
    "path": "/TROUBLESHOOTING",
    "source": "TROUBLESHOOTING.md"
  },
  {
    "title": "Glossary",
    "kind": "md",
    "path": "/GLOSSARY",
    "source": "GLOSSARY.md"
  },
  {
    "title": "Architecture Decisions",
    "kind": "md",
    "path": "/adr/",
    "source": "adr/"
  },
  {
    "title": "Roadmap",
    "kind": "section",
    "children": [
      {
        "title": "Master Roadmap",
        "kind": "md",
        "path": "/moon/ROADMAP",
        "source": "moon/ROADMAP.md"
      },
      {
        "title": "Python",
        "kind": "md",
        "path": "/moon/roadmaps/python",
        "source": "moon/roadmaps/python.md"
      },
      {
        "title": "C++",
        "kind": "md",
        "path": "/moon/roadmaps/cpp",
        "source": "moon/roadmaps/cpp.md"
      }
    ]
  },
  {
    "title": "Changelog",
    "kind": "md",
    "path": "/moon/CHANGELOG",
    "source": "moon/CHANGELOG.md"
  },
  {
    "title": "Research",
    "kind": "section",
    "children": [
      {
        "title": "ASP Comprehensive Research",
        "kind": "md",
        "path": "/research/ASP_Comprehensive_Research_Report",
        "source": "research/ASP_Comprehensive_Research_Report.md"
      },
      {
        "title": "Image Stitching Research",
        "kind": "md",
        "path": "/research/Image_Stitching_Research",
        "source": "research/Image_Stitching_Research.md"
      }
    ]
  },
  {
    "title": "Reports",
    "kind": "section",
    "children": [
      {
        "title": "ASP Critical Evaluation",
        "kind": "md",
        "path": "/reports/ASP_Critical_Evaluation_2026-07-08",
        "source": "reports/ASP_Critical_Evaluation_2026-07-08.md"
      },
      {
        "title": "Image Stitching Report",
        "kind": "md",
        "path": "/reports/image_stitching_report",
        "source": "reports/image_stitching_report.md"
      }
    ]
  },
  {
    "title": "Image-Toolkit (parent project)",
    "kind": "external",
    "href": "https://github.com/ACFHarbinger/Image-Toolkit"
  }
];

export const searchIndex: { title: string; path: string; source: string; kind: "md" | "notebook" }[] = [
  {
    "title": "Home",
    "path": "/",
    "source": "index.md",
    "kind": "md"
  },
  {
    "title": "Architecture",
    "path": "/ARCHITECTURE",
    "source": "ARCHITECTURE.md",
    "kind": "md"
  },
  {
    "title": "Development",
    "path": "/DEVELOPMENT",
    "source": "DEVELOPMENT.md",
    "kind": "md"
  },
  {
    "title": "Testing",
    "path": "/TESTING",
    "source": "TESTING.md",
    "kind": "md"
  },
  {
    "title": "Dependencies",
    "path": "/DEPENDENCIES",
    "source": "DEPENDENCIES.md",
    "kind": "md"
  },
  {
    "title": "Dependency Policy",
    "path": "/DEPENDENCY_POLICY",
    "source": "DEPENDENCY_POLICY.md",
    "kind": "md"
  },
  {
    "title": "Documentation Standards",
    "path": "/DOCUMENTATION_STANDARDS",
    "source": "DOCUMENTATION_STANDARDS.md",
    "kind": "md"
  },
  {
    "title": "Benchmarks",
    "path": "/BENCHMARKS",
    "source": "BENCHMARKS.md",
    "kind": "md"
  },
  {
    "title": "Troubleshooting",
    "path": "/TROUBLESHOOTING",
    "source": "TROUBLESHOOTING.md",
    "kind": "md"
  },
  {
    "title": "Glossary",
    "path": "/GLOSSARY",
    "source": "GLOSSARY.md",
    "kind": "md"
  },
  {
    "title": "Architecture Decisions",
    "path": "/adr/",
    "source": "adr/",
    "kind": "md"
  },
  {
    "title": "Master Roadmap",
    "path": "/moon/ROADMAP",
    "source": "moon/ROADMAP.md",
    "kind": "md"
  },
  {
    "title": "Python",
    "path": "/moon/roadmaps/python",
    "source": "moon/roadmaps/python.md",
    "kind": "md"
  },
  {
    "title": "C++",
    "path": "/moon/roadmaps/cpp",
    "source": "moon/roadmaps/cpp.md",
    "kind": "md"
  },
  {
    "title": "Changelog",
    "path": "/moon/CHANGELOG",
    "source": "moon/CHANGELOG.md",
    "kind": "md"
  },
  {
    "title": "ASP Comprehensive Research",
    "path": "/research/ASP_Comprehensive_Research_Report",
    "source": "research/ASP_Comprehensive_Research_Report.md",
    "kind": "md"
  },
  {
    "title": "Image Stitching Research",
    "path": "/research/Image_Stitching_Research",
    "source": "research/Image_Stitching_Research.md",
    "kind": "md"
  },
  {
    "title": "ASP Critical Evaluation",
    "path": "/reports/ASP_Critical_Evaluation_2026-07-08",
    "source": "reports/ASP_Critical_Evaluation_2026-07-08.md",
    "kind": "md"
  },
  {
    "title": "Image Stitching Report",
    "path": "/reports/image_stitching_report",
    "source": "reports/image_stitching_report.md",
    "kind": "md"
  }
];
